# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_ragflow_server import ragflow_service_pb2 as grpc__ragflow__server_dot_ragflow__service__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_ragflow_server/ragflow_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RagServicesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateChatCompletion = channel.unary_stream(
                '/ragflow.RagServices/CreateChatCompletion',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.CreateChatCompletionRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.ChatCompletionResponse.FromString,
                _registered_method=True)
        self.CreateAgentCompletion = channel.unary_stream(
                '/ragflow.RagServices/CreateAgentCompletion',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.CreateAgentCompletionRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.AgentCompletionResponse.FromString,
                _registered_method=True)
        self.CreateDataset = channel.unary_unary(
                '/ragflow.RagServices/CreateDataset',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.CreateDatasetRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.CreateDatasetResponse.FromString,
                _registered_method=True)
        self.DeleteDatasets = channel.unary_unary(
                '/ragflow.RagServices/DeleteDatasets',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteDatasetsRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteDatasetsResponse.FromString,
                _registered_method=True)
        self.UpdateDataset = channel.unary_unary(
                '/ragflow.RagServices/UpdateDataset',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.UpdateDatasetRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.UpdateDatasetResponse.FromString,
                _registered_method=True)
        self.ListDatasets = channel.unary_unary(
                '/ragflow.RagServices/ListDatasets',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListDatasetsRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListDatasetsResponse.FromString,
                _registered_method=True)
        self.GetDatasetKnowledgeGraph = channel.unary_unary(
                '/ragflow.RagServices/GetDatasetKnowledgeGraph',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.GetDatasetKnowledgeGraphRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.GetDatasetKnowledgeGraphResponse.FromString,
                _registered_method=True)
        self.DeleteDatasetKnowledgeGraph = channel.unary_unary(
                '/ragflow.RagServices/DeleteDatasetKnowledgeGraph',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteDatasetKnowledgeGraphRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteDatasetKnowledgeGraphResponse.FromString,
                _registered_method=True)
        self.UploadDocuments = channel.unary_unary(
                '/ragflow.RagServices/UploadDocuments',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.UploadDocumentsRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.UploadDocumentsResponse.FromString,
                _registered_method=True)
        self.UpdateDocument = channel.unary_unary(
                '/ragflow.RagServices/UpdateDocument',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.UpdateDocumentRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.UpdateDocumentResponse.FromString,
                _registered_method=True)
        self.DownloadDocument = channel.unary_unary(
                '/ragflow.RagServices/DownloadDocument',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.DownloadDocumentRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.DownloadDocumentResponse.FromString,
                _registered_method=True)
        self.ListDocuments = channel.unary_unary(
                '/ragflow.RagServices/ListDocuments',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListDocumentsRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListDocumentsResponse.FromString,
                _registered_method=True)
        self.DeleteDocuments = channel.unary_unary(
                '/ragflow.RagServices/DeleteDocuments',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteDocumentsRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteDocumentsResponse.FromString,
                _registered_method=True)
        self.ParseDocuments = channel.unary_unary(
                '/ragflow.RagServices/ParseDocuments',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.ParseDocumentsRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.ParseDocumentsResponse.FromString,
                _registered_method=True)
        self.StopParsingDocuments = channel.unary_unary(
                '/ragflow.RagServices/StopParsingDocuments',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.StopParsingDocumentsRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.StopParsingDocumentsResponse.FromString,
                _registered_method=True)
        self.AddChunk = channel.unary_unary(
                '/ragflow.RagServices/AddChunk',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.AddChunkRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.AddChunkResponse.FromString,
                _registered_method=True)
        self.ListChunks = channel.unary_unary(
                '/ragflow.RagServices/ListChunks',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListChunksRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListChunksResponse.FromString,
                _registered_method=True)
        self.DeleteChunks = channel.unary_unary(
                '/ragflow.RagServices/DeleteChunks',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteChunksRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteChunksResponse.FromString,
                _registered_method=True)
        self.UpdateChunk = channel.unary_unary(
                '/ragflow.RagServices/UpdateChunk',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.UpdateChunkRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.UpdateChunkResponse.FromString,
                _registered_method=True)
        self.RetrieveChunks = channel.unary_unary(
                '/ragflow.RagServices/RetrieveChunks',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.RetrieveChunksRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.RetrieveChunksResponse.FromString,
                _registered_method=True)
        self.CreateChatAssistant = channel.unary_unary(
                '/ragflow.RagServices/CreateChatAssistant',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.CreateChatAssistantRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.CreateChatAssistantResponse.FromString,
                _registered_method=True)
        self.UpdateChatAssistant = channel.unary_unary(
                '/ragflow.RagServices/UpdateChatAssistant',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.UpdateChatAssistantRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.UpdateChatAssistantResponse.FromString,
                _registered_method=True)
        self.DeleteChatAssistants = channel.unary_unary(
                '/ragflow.RagServices/DeleteChatAssistants',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteChatAssistantsRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteChatAssistantsResponse.FromString,
                _registered_method=True)
        self.ListChatAssistants = channel.unary_unary(
                '/ragflow.RagServices/ListChatAssistants',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListChatAssistantsRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListChatAssistantsResponse.FromString,
                _registered_method=True)
        self.CreateSessionWithChatAssistant = channel.unary_unary(
                '/ragflow.RagServices/CreateSessionWithChatAssistant',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.CreateSessionWithChatAssistantRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.CreateSessionWithChatAssistantResponse.FromString,
                _registered_method=True)
        self.UpdateChatAssistantSession = channel.unary_unary(
                '/ragflow.RagServices/UpdateChatAssistantSession',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.UpdateChatAssistantSessionRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.UpdateChatAssistantSessionResponse.FromString,
                _registered_method=True)
        self.ListChatAssistantSessions = channel.unary_unary(
                '/ragflow.RagServices/ListChatAssistantSessions',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListChatAssistantSessionsRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListChatAssistantSessionsResponse.FromString,
                _registered_method=True)
        self.DeleteChatAssistantSessions = channel.unary_unary(
                '/ragflow.RagServices/DeleteChatAssistantSessions',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteChatAssistantSessionsRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteChatAssistantSessionsResponse.FromString,
                _registered_method=True)
        self.ConverseWithChatAssistant = channel.unary_stream(
                '/ragflow.RagServices/ConverseWithChatAssistant',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.ConverseWithChatAssistantRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.ConverseWithChatAssistantResponse.FromString,
                _registered_method=True)
        self.CreateSessionWithAgent = channel.unary_unary(
                '/ragflow.RagServices/CreateSessionWithAgent',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.CreateSessionWithAgentRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.CreateSessionWithAgentResponse.FromString,
                _registered_method=True)
        self.ConverseWithAgent = channel.unary_stream(
                '/ragflow.RagServices/ConverseWithAgent',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.ConverseWithAgentRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.ConverseWithAgentResponse.FromString,
                _registered_method=True)
        self.ListAgentSessions = channel.unary_unary(
                '/ragflow.RagServices/ListAgentSessions',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListAgentSessionsRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListAgentSessionsResponse.FromString,
                _registered_method=True)
        self.DeleteAgentSessions = channel.unary_unary(
                '/ragflow.RagServices/DeleteAgentSessions',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteAgentSessionsRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteAgentSessionsResponse.FromString,
                _registered_method=True)
        self.GenerateRelatedQuestions = channel.unary_unary(
                '/ragflow.RagServices/GenerateRelatedQuestions',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.GenerateRelatedQuestionsRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.GenerateRelatedQuestionsResponse.FromString,
                _registered_method=True)
        self.ListAgents = channel.unary_unary(
                '/ragflow.RagServices/ListAgents',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListAgentsRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListAgentsResponse.FromString,
                _registered_method=True)
        self.CreateAgent = channel.unary_unary(
                '/ragflow.RagServices/CreateAgent',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.CreateAgentRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.CreateAgentResponse.FromString,
                _registered_method=True)
        self.UpdateAgent = channel.unary_unary(
                '/ragflow.RagServices/UpdateAgent',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.UpdateAgentRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.UpdateAgentResponse.FromString,
                _registered_method=True)
        self.DeleteAgent = channel.unary_unary(
                '/ragflow.RagServices/DeleteAgent',
                request_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteAgentRequest.SerializeToString,
                response_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteAgentResponse.FromString,
                _registered_method=True)


class RagServicesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateChatCompletion(self, request, context):
        """OpenAI-Compatible API
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAgentCompletion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDataset(self, request, context):
        """Dataset Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDatasets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDatasets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDatasetKnowledgeGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDatasetKnowledgeGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadDocuments(self, request, context):
        """Document Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParseDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopParsingDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddChunk(self, request, context):
        """Chunk Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChunks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteChunks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveChunks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateChatAssistant(self, request, context):
        """Chat Assistant Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateChatAssistant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteChatAssistants(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChatAssistants(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSessionWithChatAssistant(self, request, context):
        """Session Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateChatAssistantSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChatAssistantSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteChatAssistantSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConverseWithChatAssistant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSessionWithAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConverseWithAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgentSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAgentSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateRelatedQuestions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgents(self, request, context):
        """Agent Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RagServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateChatCompletion': grpc.unary_stream_rpc_method_handler(
                    servicer.CreateChatCompletion,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.CreateChatCompletionRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.ChatCompletionResponse.SerializeToString,
            ),
            'CreateAgentCompletion': grpc.unary_stream_rpc_method_handler(
                    servicer.CreateAgentCompletion,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.CreateAgentCompletionRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.AgentCompletionResponse.SerializeToString,
            ),
            'CreateDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDataset,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.CreateDatasetRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.CreateDatasetResponse.SerializeToString,
            ),
            'DeleteDatasets': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDatasets,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteDatasetsRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteDatasetsResponse.SerializeToString,
            ),
            'UpdateDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDataset,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.UpdateDatasetRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.UpdateDatasetResponse.SerializeToString,
            ),
            'ListDatasets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDatasets,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListDatasetsRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListDatasetsResponse.SerializeToString,
            ),
            'GetDatasetKnowledgeGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDatasetKnowledgeGraph,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.GetDatasetKnowledgeGraphRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.GetDatasetKnowledgeGraphResponse.SerializeToString,
            ),
            'DeleteDatasetKnowledgeGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDatasetKnowledgeGraph,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteDatasetKnowledgeGraphRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteDatasetKnowledgeGraphResponse.SerializeToString,
            ),
            'UploadDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadDocuments,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.UploadDocumentsRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.UploadDocumentsResponse.SerializeToString,
            ),
            'UpdateDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDocument,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.UpdateDocumentRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.UpdateDocumentResponse.SerializeToString,
            ),
            'DownloadDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadDocument,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.DownloadDocumentRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.DownloadDocumentResponse.SerializeToString,
            ),
            'ListDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDocuments,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListDocumentsRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListDocumentsResponse.SerializeToString,
            ),
            'DeleteDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDocuments,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteDocumentsRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteDocumentsResponse.SerializeToString,
            ),
            'ParseDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseDocuments,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.ParseDocumentsRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.ParseDocumentsResponse.SerializeToString,
            ),
            'StopParsingDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.StopParsingDocuments,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.StopParsingDocumentsRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.StopParsingDocumentsResponse.SerializeToString,
            ),
            'AddChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.AddChunk,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.AddChunkRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.AddChunkResponse.SerializeToString,
            ),
            'ListChunks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChunks,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListChunksRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListChunksResponse.SerializeToString,
            ),
            'DeleteChunks': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteChunks,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteChunksRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteChunksResponse.SerializeToString,
            ),
            'UpdateChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateChunk,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.UpdateChunkRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.UpdateChunkResponse.SerializeToString,
            ),
            'RetrieveChunks': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveChunks,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.RetrieveChunksRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.RetrieveChunksResponse.SerializeToString,
            ),
            'CreateChatAssistant': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChatAssistant,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.CreateChatAssistantRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.CreateChatAssistantResponse.SerializeToString,
            ),
            'UpdateChatAssistant': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateChatAssistant,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.UpdateChatAssistantRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.UpdateChatAssistantResponse.SerializeToString,
            ),
            'DeleteChatAssistants': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteChatAssistants,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteChatAssistantsRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteChatAssistantsResponse.SerializeToString,
            ),
            'ListChatAssistants': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChatAssistants,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListChatAssistantsRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListChatAssistantsResponse.SerializeToString,
            ),
            'CreateSessionWithChatAssistant': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSessionWithChatAssistant,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.CreateSessionWithChatAssistantRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.CreateSessionWithChatAssistantResponse.SerializeToString,
            ),
            'UpdateChatAssistantSession': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateChatAssistantSession,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.UpdateChatAssistantSessionRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.UpdateChatAssistantSessionResponse.SerializeToString,
            ),
            'ListChatAssistantSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChatAssistantSessions,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListChatAssistantSessionsRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListChatAssistantSessionsResponse.SerializeToString,
            ),
            'DeleteChatAssistantSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteChatAssistantSessions,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteChatAssistantSessionsRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteChatAssistantSessionsResponse.SerializeToString,
            ),
            'ConverseWithChatAssistant': grpc.unary_stream_rpc_method_handler(
                    servicer.ConverseWithChatAssistant,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.ConverseWithChatAssistantRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.ConverseWithChatAssistantResponse.SerializeToString,
            ),
            'CreateSessionWithAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSessionWithAgent,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.CreateSessionWithAgentRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.CreateSessionWithAgentResponse.SerializeToString,
            ),
            'ConverseWithAgent': grpc.unary_stream_rpc_method_handler(
                    servicer.ConverseWithAgent,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.ConverseWithAgentRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.ConverseWithAgentResponse.SerializeToString,
            ),
            'ListAgentSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgentSessions,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListAgentSessionsRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListAgentSessionsResponse.SerializeToString,
            ),
            'DeleteAgentSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAgentSessions,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteAgentSessionsRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteAgentSessionsResponse.SerializeToString,
            ),
            'GenerateRelatedQuestions': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateRelatedQuestions,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.GenerateRelatedQuestionsRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.GenerateRelatedQuestionsResponse.SerializeToString,
            ),
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListAgentsRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.ListAgentsResponse.SerializeToString,
            ),
            'CreateAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAgent,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.CreateAgentRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.CreateAgentResponse.SerializeToString,
            ),
            'UpdateAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAgent,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.UpdateAgentRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.UpdateAgentResponse.SerializeToString,
            ),
            'DeleteAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAgent,
                    request_deserializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteAgentRequest.FromString,
                    response_serializer=grpc__ragflow__server_dot_ragflow__service__pb2.DeleteAgentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ragflow.RagServices', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ragflow.RagServices', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RagServices(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateChatCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ragflow.RagServices/CreateChatCompletion',
            grpc__ragflow__server_dot_ragflow__service__pb2.CreateChatCompletionRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.ChatCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAgentCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ragflow.RagServices/CreateAgentCompletion',
            grpc__ragflow__server_dot_ragflow__service__pb2.CreateAgentCompletionRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.AgentCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/CreateDataset',
            grpc__ragflow__server_dot_ragflow__service__pb2.CreateDatasetRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.CreateDatasetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDatasets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/DeleteDatasets',
            grpc__ragflow__server_dot_ragflow__service__pb2.DeleteDatasetsRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.DeleteDatasetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/UpdateDataset',
            grpc__ragflow__server_dot_ragflow__service__pb2.UpdateDatasetRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.UpdateDatasetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDatasets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/ListDatasets',
            grpc__ragflow__server_dot_ragflow__service__pb2.ListDatasetsRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.ListDatasetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDatasetKnowledgeGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/GetDatasetKnowledgeGraph',
            grpc__ragflow__server_dot_ragflow__service__pb2.GetDatasetKnowledgeGraphRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.GetDatasetKnowledgeGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDatasetKnowledgeGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/DeleteDatasetKnowledgeGraph',
            grpc__ragflow__server_dot_ragflow__service__pb2.DeleteDatasetKnowledgeGraphRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.DeleteDatasetKnowledgeGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/UploadDocuments',
            grpc__ragflow__server_dot_ragflow__service__pb2.UploadDocumentsRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.UploadDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/UpdateDocument',
            grpc__ragflow__server_dot_ragflow__service__pb2.UpdateDocumentRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.UpdateDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/DownloadDocument',
            grpc__ragflow__server_dot_ragflow__service__pb2.DownloadDocumentRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.DownloadDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/ListDocuments',
            grpc__ragflow__server_dot_ragflow__service__pb2.ListDocumentsRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.ListDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/DeleteDocuments',
            grpc__ragflow__server_dot_ragflow__service__pb2.DeleteDocumentsRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.DeleteDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ParseDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/ParseDocuments',
            grpc__ragflow__server_dot_ragflow__service__pb2.ParseDocumentsRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.ParseDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopParsingDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/StopParsingDocuments',
            grpc__ragflow__server_dot_ragflow__service__pb2.StopParsingDocumentsRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.StopParsingDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/AddChunk',
            grpc__ragflow__server_dot_ragflow__service__pb2.AddChunkRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.AddChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/ListChunks',
            grpc__ragflow__server_dot_ragflow__service__pb2.ListChunksRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.ListChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/DeleteChunks',
            grpc__ragflow__server_dot_ragflow__service__pb2.DeleteChunksRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.DeleteChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/UpdateChunk',
            grpc__ragflow__server_dot_ragflow__service__pb2.UpdateChunkRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.UpdateChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/RetrieveChunks',
            grpc__ragflow__server_dot_ragflow__service__pb2.RetrieveChunksRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.RetrieveChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateChatAssistant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/CreateChatAssistant',
            grpc__ragflow__server_dot_ragflow__service__pb2.CreateChatAssistantRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.CreateChatAssistantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateChatAssistant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/UpdateChatAssistant',
            grpc__ragflow__server_dot_ragflow__service__pb2.UpdateChatAssistantRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.UpdateChatAssistantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteChatAssistants(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/DeleteChatAssistants',
            grpc__ragflow__server_dot_ragflow__service__pb2.DeleteChatAssistantsRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.DeleteChatAssistantsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChatAssistants(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/ListChatAssistants',
            grpc__ragflow__server_dot_ragflow__service__pb2.ListChatAssistantsRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.ListChatAssistantsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSessionWithChatAssistant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/CreateSessionWithChatAssistant',
            grpc__ragflow__server_dot_ragflow__service__pb2.CreateSessionWithChatAssistantRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.CreateSessionWithChatAssistantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateChatAssistantSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/UpdateChatAssistantSession',
            grpc__ragflow__server_dot_ragflow__service__pb2.UpdateChatAssistantSessionRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.UpdateChatAssistantSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChatAssistantSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/ListChatAssistantSessions',
            grpc__ragflow__server_dot_ragflow__service__pb2.ListChatAssistantSessionsRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.ListChatAssistantSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteChatAssistantSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/DeleteChatAssistantSessions',
            grpc__ragflow__server_dot_ragflow__service__pb2.DeleteChatAssistantSessionsRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.DeleteChatAssistantSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConverseWithChatAssistant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ragflow.RagServices/ConverseWithChatAssistant',
            grpc__ragflow__server_dot_ragflow__service__pb2.ConverseWithChatAssistantRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.ConverseWithChatAssistantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSessionWithAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/CreateSessionWithAgent',
            grpc__ragflow__server_dot_ragflow__service__pb2.CreateSessionWithAgentRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.CreateSessionWithAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConverseWithAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ragflow.RagServices/ConverseWithAgent',
            grpc__ragflow__server_dot_ragflow__service__pb2.ConverseWithAgentRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.ConverseWithAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgentSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/ListAgentSessions',
            grpc__ragflow__server_dot_ragflow__service__pb2.ListAgentSessionsRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.ListAgentSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAgentSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/DeleteAgentSessions',
            grpc__ragflow__server_dot_ragflow__service__pb2.DeleteAgentSessionsRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.DeleteAgentSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateRelatedQuestions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/GenerateRelatedQuestions',
            grpc__ragflow__server_dot_ragflow__service__pb2.GenerateRelatedQuestionsRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.GenerateRelatedQuestionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/ListAgents',
            grpc__ragflow__server_dot_ragflow__service__pb2.ListAgentsRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.ListAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/CreateAgent',
            grpc__ragflow__server_dot_ragflow__service__pb2.CreateAgentRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.CreateAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/UpdateAgent',
            grpc__ragflow__server_dot_ragflow__service__pb2.UpdateAgentRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.UpdateAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragflow.RagServices/DeleteAgent',
            grpc__ragflow__server_dot_ragflow__service__pb2.DeleteAgentRequest.SerializeToString,
            grpc__ragflow__server_dot_ragflow__service__pb2.DeleteAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
